---
title: "Материалы"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---
### Занятие 13 января 

<a href="polit_methods_intro.pdf" title=>введение </a>

<a href="polit_lecture1.pdf" title=>лекция 1</a>

<a href="polit_hw1_2021.pdf" title=>домашнее задание 1</a>

### Занятие 20 января 

<a href=" hw1.ipynb" title=> код к ДЗ1 </a>

<a href="polit_methods_lecture2.pdf" title=>лекция 2</a>

<a href="polit_hw2_2021.pdf" title=>домашнее задание 2</a>

<a href="CoinProblem.ipynb" title=>разбор задачи про монету</a>

### Занятие 27 января 

<a href="polit_lecture3.pdf" title=> лекция 3</a>

<a href="MApolit_seminar1.pdf" title=> семинар 1</a>

### Занятие 4 февраля

<a href="polit_methods_hw.pdf" title=> Задания для практики</a>

Reading: 

<a href="Brambor_Clark_Golder.pdf" title=> Bramb et al.</a>

<a href="presentation_Brambor et al..pdf" title=> Презентация по Brambor et al. </a>

<a href="Franzese, Kam.pdf" title=> Franzese, Kam, pp. 19 - 39 </a>

### Занятие 10 февраля

<a href="MApolit_lab1.ipynb" title=> Lab1. Interaction effects</a>

<a href="lab1.dta" title=> lab1.dta</a>

<a href="for_practice.pdf" title=> Задачи для практики перед проверочной</a>

Домашнее задание -- нужно сдать на проверку до 23.59 21 февраля: 

1 уровень: 

<a href="hw_inter_1.ipynb" title=> Условие заданий </a>

<a href="hw_inter_1.dta" title=> hw_inter_1.dta </a>

2 уровень (на бонусные баллы): 

<a href="hw_inter_2.ipynb" title=> Условие заданий </a>

<a href="hw_inter_2.dta" title=> hw_inter_2.dta</a>

### Занятия 17 и 24 февраля

<a href="MApolit_lecture3.pdf" title=> лекция 4</a>

<a href="MApolit_seminar2.pdf" title=> семинар 2</a>

<a href="MApolit_lab2.ipynb" title=> Lab2. FE-models (part 1)</a>

<a href="lab2.dta" title=> lab2.dta</a>

Бонусное домашнее задание (Дедлайн: 23.59 7 марта)

<a href="hwbonus" title=> Условие бонусного ДЗ</a>

<a href="hwbonus.dta" title=> hwbonus.dta</a>

### Занятия 3 и 10 марта

<a href="FE__RE_models.pdf" title=> лекция 5</a>

<a href="MApolit_lab3.ipynb" title=> Lab3. FE-models (part 2)</a>

Домашнее задание (дедлайн - 28 марта):

<a href="MApolit_hw2.ipynb" title=> Домашнее задание 2 (обязательное) </a>

<a href="MApolit_hw2.dta" title=> MApolit_hw2.dta </a>

